# Generated by Django 5.1.2 on 2024-11-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('pos_z', models.IntegerField()),
                ('color', models.CharField(max_length=8)),
            ],
        ),
    ]
